<a href="https://colab.research.google.com/github/Seeeeiu/Python/blob/master/Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 3

In [79]:
import keras
keras.__version__

'2.2.4'

In [0]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

## Example Problem:

#### Specify Model Architecture

In [0]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

#### Compile Model 

In [0]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

#### Reshape and Scale Features

In [0]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

#### Convert Labels to Dummy Variables

In [0]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

#### Train the Network

In [85]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 2s 38us/step - loss: 0.2582 - acc: 0.9250
Epoch 2/5
60000/60000 [==============================] - 2s 34us/step - loss: 0.1033 - acc: 0.9691
Epoch 3/5
60000/60000 [==============================] - 2s 34us/step - loss: 0.0680 - acc: 0.9802
Epoch 4/5
60000/60000 [==============================] - 2s 35us/step - loss: 0.0495 - acc: 0.9850
Epoch 5/5
60000/60000 [==============================] - 2s 35us/step - loss: 0.0381 - acc: 0.9887


#### Evaluate the Test Data

In [76]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

10000/10000 [==============================] - 1s 54us/step
test_acc: 0.9796


## Problem 1:

a. Modify the example model above to contain 3 hidden layers of 512 neurons each.  


In [0]:
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

b. Specify the time elapsed to train the new model with 5 epochs.

In [99]:
import time as t
now=t.time()
network.fit(train_images, train_labels, epochs=5, batch_size=128)
elapsed = t.time()-now
elapsed

Epoch 1/5
60000/60000 [==============================] - 3s 49us/step - loss: 0.0819 - acc: 0.9744
Epoch 2/5
60000/60000 [==============================] - 3s 49us/step - loss: 0.0683 - acc: 0.9791
Epoch 3/5
60000/60000 [==============================] - 3s 49us/step - loss: 0.0579 - acc: 0.9813
Epoch 4/5
60000/60000 [==============================] - 3s 49us/step - loss: 0.0496 - acc: 0.9847
Epoch 5/5
60000/60000 [==============================] - 3s 49us/step - loss: 0.0406 - acc: 0.9872


14.727256298065186

c. Specify the accuracy on the test data.

In [92]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

10000/10000 [==============================] - 1s 62us/step
test_acc: 0.9791


d. Specify the number of parameters in the new model.

In [94]:
network.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_21 (Dense)             (None, 512)               401920    
_________________________________________________________________
dense_22 (Dense)             (None, 512)               262656    
_________________________________________________________________
dense_23 (Dense)             (None, 512)               262656    
_________________________________________________________________
dense_24 (Dense)             (None, 10)                5130      
Total params: 932,362
Trainable params: 932,362
Non-trainable params: 0
_________________________________________________________________


e. If you rerun the fit command, you will begin from the weights you left off with.  Fit the network further by running 5 more epochs.  Then specify the new test accuracy.

In [95]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 3s 49us/step - loss: 0.0344 - acc: 0.9907
Epoch 2/5
60000/60000 [==============================] - 3s 48us/step - loss: 0.0312 - acc: 0.9920
Epoch 3/5
60000/60000 [==============================] - 3s 49us/step - loss: 0.0284 - acc: 0.9932
Epoch 4/5
60000/60000 [==============================] - 3s 49us/step - loss: 0.0275 - acc: 0.9934
Epoch 5/5
60000/60000 [==============================] - 3s 48us/step - loss: 0.0260 - acc: 0.9941


In [96]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

10000/10000 [==============================] - 1s 54us/step
test_acc: 0.9819


f. How does the training accuracy compare with the test set accuracy?

## Problem 2:

a. Modify the original example problem to use sigmoid nurons in the hidden layer.  How does the accuracy and the (model train) time elapsed compare to the original example?  How do the number of parameters compare?

In [103]:
network = models.Sequential()
network.add(layers.Dense(512, activation='sigmoid', input_shape=(28 * 28,)))
network.add(layers.Dense(512, activation='sigmoid', input_shape=(28 * 28,)))
network.add(layers.Dense(512, activation='sigmoid', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

import time as t
now=t.time()
network.fit(train_images, train_labels, epochs=5, batch_size=128)
elapsed = t.time()-now
print(elapsed)

test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)
network.summary()



Epoch 1/5
60000/60000 [==============================] - 3s 54us/step - loss: 0.6028 - acc: 0.8034
Epoch 2/5
60000/60000 [==============================] - 3s 49us/step - loss: 0.2298 - acc: 0.9289
Epoch 3/5
60000/60000 [==============================] - 3s 49us/step - loss: 0.1621 - acc: 0.9502
Epoch 4/5
60000/60000 [==============================] - 3s 49us/step - loss: 0.1233 - acc: 0.9622
Epoch 5/5
60000/60000 [==============================] - 3s 50us/step - loss: 0.0988 - acc: 0.9693


15.42881727218628

b. Modify the original example problem to use elu nurons in the hidden layer.  How does the accuracy and the (model train) time elapsed compare to the original example?  How do the number of parameters compare?

In [104]:
network = models.Sequential()
network.add(layers.Dense(512, activation='elu', input_shape=(28 * 28,)))
network.add(layers.Dense(512, activation='elu', input_shape=(28 * 28,)))
network.add(layers.Dense(512, activation='elu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

import time as t
now=t.time()
network.fit(train_images, train_labels, epochs=5, batch_size=128)
elapsed = t.time()-now
print(elapsed)

test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)
network.summary()


Epoch 1/5
60000/60000 [==============================] - 3s 57us/step - loss: 0.3382 - acc: 0.8958
Epoch 2/5
60000/60000 [==============================] - 3s 49us/step - loss: 0.1430 - acc: 0.9570
Epoch 3/5
60000/60000 [==============================] - 3s 49us/step - loss: 0.1026 - acc: 0.9689
Epoch 4/5
60000/60000 [==============================] - 3s 49us/step - loss: 0.0820 - acc: 0.9753
Epoch 5/5
60000/60000 [==============================] - 3s 49us/step - loss: 0.0676 - acc: 0.9802
15.46489953994751
10000/10000 [==============================] - 1s 68us/step
test_acc: 0.9709
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_37 (Dense)             (None, 512)               401920    
_________________________________________________________________
dense_38 (Dense)             (None, 512)               262656    
_________________________________________________________________
dense_39 (Dens

c. Modify the original example problem to use the adam optimizer.  How does the accuracy and the (model train) time elapsed compare to the original example?  How do the number of parameters compare?

In [105]:
network = models.Sequential()
network.add(layers.Dense(512, activation='elu', input_shape=(28 * 28,)))
network.add(layers.Dense(512, activation='elu', input_shape=(28 * 28,)))
network.add(layers.Dense(512, activation='elu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

network.compile(optimizer='adam',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

import time as t
now=t.time()
network.fit(train_images, train_labels, epochs=5, batch_size=128)
elapsed = t.time()-now
print(elapsed)

test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)
network.summary()

Epoch 1/5
60000/60000 [==============================] - 4s 63us/step - loss: 0.2680 - acc: 0.9196
Epoch 2/5
60000/60000 [==============================] - 3s 54us/step - loss: 0.1249 - acc: 0.9606
Epoch 3/5
60000/60000 [==============================] - 3s 54us/step - loss: 0.0899 - acc: 0.9711
Epoch 4/5
60000/60000 [==============================] - 3s 54us/step - loss: 0.0739 - acc: 0.9767
Epoch 5/5
60000/60000 [==============================] - 3s 54us/step - loss: 0.0682 - acc: 0.9785
17.354662656784058
10000/10000 [==============================] - 1s 75us/step
test_acc: 0.9751
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_41 (Dense)             (None, 512)               401920    
_________________________________________________________________
dense_42 (Dense)             (None, 512)               262656    
_________________________________________________________________
dense_43 (Den

d. Modify the original example problem to include a second hidden layer with 300 relu neurons, a third hidden layer with 200 neurons and a fourth hidden layer with 100 neurons.  How does the accuracy and the (model train) time elapsed compare to the original example?  How do the number of parameters compare?

In [0]:
network = models.Sequential()
network.add(layers.Dense(512, activation='elu', input_shape=(28 * 28,)))
network.add(layers.Dense(300, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(200, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(100, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

import time as t
now=t.time()
network.fit(train_images, train_labels, epochs=5, batch_size=128)
elapsed = t.time()-now
print(elapsed)

test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)
network.summary()

## Problem 3:

Now create your own neural network based upon the concepts you learned.  Achieve a higher accuracy than 98% on the test set.

## Problem 4:

Last year as part of the final exam in Machine Learning I hosted a Kaggle competition on the Plankton challenge: https://www.kaggle.com/t/830c8dd97ae748f8bd3fd52e8ccca849

a. **Using only the first 1600 features**, use the keras methods and models that have been used thus far make a submission to the competition.  Report your accuracy (your score will not show on the leaderboard since this competition is closed).

b. Try another method that you think would be interesting (you can do whatever model/features you want for this problem but it must be different than the previous problem).  

## Problem 5:

For this problem we will be working with model churn data. Import the libraries and load in the model churn data by running the next 2 following code chunks.

In [0]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [9]:
import pandas as pd
import io

from google.colab import drive
drive.mount('/content/gdrive')

dataset = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/Churn_Modelling.csv', sep=',', decimal='.')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


a. Show the first 10 observations of the original data set (dataset).

In [10]:
dataset.iloc[0:10,:]

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

b. Which 3 columns should not be used as features? Create the appropriate X matrix (including categorical variables) and the y vector as the last column.

In [0]:
#RowNumber CustomerId Surname
X = dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values

c. Print out the first 10 observations (and the first 6 columns) of the X matrix and comment on the number of observations and number of columns.

In [46]:
print(X[:10,0:6])
print(X.shape)

[[619 'France' 'Female' 42 2 0.0]
 [608 'Spain' 'Female' 41 1 83807.86]
 [502 'France' 'Female' 42 8 159660.8]
 [699 'France' 'Female' 39 1 0.0]
 [850 'Spain' 'Female' 43 2 125510.82]
 [645 'Spain' 'Male' 44 8 113755.78]
 [822 'France' 'Male' 50 7 0.0]
 [376 'Germany' 'Female' 29 4 115046.74]
 [501 'France' 'Male' 44 4 142051.07]
 [684 'France' 'Male' 27 2 134603.88]]
(10000, 10)


d. After running the following code in the next code chunk, print out the first 10 observations (and the first 6 columns).  Also, print out the shape of the X matrix.

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelEncoderX1=LabelEncoder()
X[:,1]=labelEncoderX1.fit_transform(X[:,1])

labelEncoderX1=LabelEncoder()
X[:,2]=labelEncoderX1.fit_transform(X[:,2])

In [48]:
print(X[:10,0:6])
print(X.shape)

[[619 0 0 42 2 0.0]
 [608 2 0 41 1 83807.86]
 [502 0 0 42 8 159660.8]
 [699 0 0 39 1 0.0]
 [850 2 0 43 2 125510.82]
 [645 2 1 44 8 113755.78]
 [822 0 1 50 7 0.0]
 [376 1 0 29 4 115046.74]
 [501 0 1 44 4 142051.07]
 [684 0 1 27 2 134603.88]]
(10000, 10)


e. How do the X matrices from c and d compare? What does the one in column 2 denote?

f. Run the following code and again print out the first 10 observations and 6 columns. Also print the shape of the X matrix.

In [49]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [51]:
print(X[:10,0:6])
print(X.shape)

[[  0.   0. 619.   0.  42.   2.]
 [  0.   1. 608.   0.  41.   1.]
 [  0.   0. 502.   0.  42.   8.]
 [  0.   0. 699.   0.  39.   1.]
 [  0.   1. 850.   0.  43.   2.]
 [  0.   1. 645.   1.  44.   8.]
 [  0.   0. 822.   1.  50.   7.]
 [  1.   0. 376.   0.  29.   4.]
 [  0.   0. 501.   1.  44.   4.]
 [  0.   0. 684.   1.  27.   2.]]
(10000, 11)


g. Explain why we should get rid of the first column.  Get rid of the first column in the X matrix.  Print out the first 6 observations after getting rid of the first column.

In [50]:
X = X[:,1:]
print(X[:6,:])

[[0.0000000e+00 0.0000000e+00 6.1900000e+02 0.0000000e+00 4.2000000e+01
  2.0000000e+00 0.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00
  1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 0.0000000e+00 4.1000000e+01
  1.0000000e+00 8.3807860e+04 1.0000000e+00 0.0000000e+00 1.0000000e+00
  1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 0.0000000e+00 4.2000000e+01
  8.0000000e+00 1.5966080e+05 3.0000000e+00 1.0000000e+00 0.0000000e+00
  1.1393157e+05]
 [0.0000000e+00 0.0000000e+00 6.9900000e+02 0.0000000e+00 3.9000000e+01
  1.0000000e+00 0.0000000e+00 2.0000000e+00 0.0000000e+00 0.0000000e+00
  9.3826630e+04]
 [0.0000000e+00 1.0000000e+00 8.5000000e+02 0.0000000e+00 4.3000000e+01
  2.0000000e+00 1.2551082e+05 1.0000000e+00 1.0000000e+00 1.0000000e+00
  7.9084100e+04]
 [0.0000000e+00 1.0000000e+00 6.4500000e+02 1.0000000e+00 4.4000000e+01
  8.0000000e+00 1.1375578e+05 2.0000000e+00 1.0000000e+00 0.0000000e+00
  1.4975671e+05]]


h. Perform a train_test_split with test set of 20% of the data.

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2, random_state = 0 ) # random_state:setting the seed 

i. Below is code to scale the features in both the training and testing set using the StandardScaler. What is the difference between fitting the transform (fit_transform) and applying the transform (transform)?

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

j. Use keras to train a model and report the test set accuracy.

## Problem 6:

For the breast cancer dataset (available at https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29) do the following:
* Use column 1 as the response variable and all other values (except column 0) as features
* Scale the feature variables
* Split the data with 75% of the training data in the training set and 25% in the test set
* Apply PCA to the training set so that 90% of the variance is retained
* Apply neural networks to the training PCA dataset to predict the response variable
* Predict the test data set and print out the accuracy

In [0]:
dataset = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/breastcancer.csv', sep=',', decimal='.')